# Connection settings for the Radio REST API
rest_api:
  # URL at which the API can be found
  url: https://api.example.com/v2
  # Username and password used to authenticate with the API
  user: hackme
  password: hackme

# Connection settings for the PostgreSQL database
db:
  # The host where the database is located. Remove the line if the host is
  # localhost.
  host: "db.example.com"
  # Port to use for connections. 5432 is the default.
  port: 5432
  # Database to use
  database: podcastdb
  # Username and password used to authenticate with the database
  user: hackme
  password: hackme

# Global settings for the episode and show processors.
processors:
  # When a processor exists as both a show and an episode processor, its
  # global settings will be shared between the two versions.

  # Some settings are observed by all processors. They are:
  # bypass_show: List of show IDs to bypass (for show processors).
  # bypass_episode: List of episode URLs to bypass (for episode processors).
  # start_date: YYYY-MM-DD for the first date of episodes to process. Beginning
  #   of time assumed if not present.
  # end_date: YYYY-MM-DD for the last date of episodes to process. End of time
  #   assumed if not present.

  # Format:
  # ClassName:
  #   setting1: value1
  #   setting2: value2
  Chimera:
    api: https://filer.radiorevolt.no/dusken_radio_api_legacy
    start_date: 2013-02-28  # Derived from when Filmofil has native Chimera-metadata

  SetDefaults:
    description: Podkast fra Radio Revolt
    image: "http://filer.radiorevolt.no/bilder/default_podkastlogo.png"
    category:
      category: Education
      subcategory: Higher Education
    language: "no"  # "no" without quotes would be parsed as boolean false
    website: "https://radiorevolt.no/"
    authors:
      - name: Radio Revolt
        email: radioredaktor@studentmediene.no
    web_master:
      name: Radio Revolt
      email: teknisk@studentmediene.no
    owner:
      name: Radio Revolt
      email: teknisk@studentmediene.no
    explicit: false

  Kapina:
    api: https://radiorevolt.no/graphql/
    show_url_template: https://radiorevolt.no/programmer/%s
    image_template: https://radiorevolt.no%s

  ManualChanges:
    episode_file: manual_changes.json
    show_file: manual_changes.json


# Configuration of the processing pipelines

# Each pipeline represents one sequence of processors which are applied one
# after another on either shows or episodes. They do stuff like find metadata
# or hold back episodes which should not be published.

# We have different pipelines. Their use is described below.

# You may set local settings for the processors that are set up, which override
# their global settings (see above). This way, you may use a processor multiple
# times, but with different settings. This is true even within the same
# pipeline. Observed settings are the same.
# Note that the overwriting logic is dead simple, so if you define a bypass list
# here, it will overwrite the entire bypass list defined globally, so you'll
# need to list them all again.

# All classes defined inside the episode_processors and show_processors
# directories are automatically available for use as processors.

# It is possible to reuse pipelines inside another pipeline. This is done by
# writing the pipeline's name in place of a processor class name. You may also
# create additional pipelines for the purpose of sharing them among multiple
# pipelines, but their name should start with an underscore to signal that they
# are not used directly by the application.

# Format:
# pipelines:
#   show or episode:
#     name_of_pipeline:
#       - Processor1ClassName:
#           setting1: value1
#           setting2: value2
#           ...
#       - Processor2ClassName:
#           setting1: value1
#           setting2: value2
#           ...
#       - name_of_other_pipeline
#       ...
#       - Processor3ClassNameWithoutLocalSettings
#       - Processor4ClassNameWithoutLocalSettings
#       ...
#     name_of_pipeline_2:
#        ...
pipelines:
  # Pipelines for shows
  show:
    # Pipeline used when serving feeds for listeners
    web:
      - _basis
      - UseLocalImage

    # Pipeline used when serving the special "all episodes" feed for listeners.
    all_feed:
      - SetDefaults

    # Pipeline used when processing shows to look for images which needs to be
    # processed. The UseLocalImage processor should not occur here, since it
    # would interfere with the image processing.
    image_processing:
      - _basis

    # Internal pipeline shared by web and image_processing
    _basis:
      - Chimera
      - SetDefaults
      - ManualChanges

  # Pipelines for episodes
  episode:
    # The pipeline used for episodes when serving feeds directly to listeners.
    web:
      - _basis

    # Pipeline used when serving feeds to be relayed by Spotify.
    spotify:
      # Skip until a certain date, but use different dates for different shows.
      # (To not skip anything, bypass the show rather than specify an early date)
      - SkipByDate:
          default: 2018-02-01
          232: 2017-10-26  # Filmofil
          2674: 2017-10-22 # Rødmaling
          2694: 2017-10-23 # 67% Sikkert
          2673: 2017-09-17 # Satirikon
          1957: 2017-10-19 # Uillustrert vitenskap
          2412: 2018-01-18 # Nesten Helg
          1980: 2017-10-16 # Bokbaren
          2676: 2018-01-16 # Millennium
      - _basis

    # Internal pipeline shared by web and spotify
    _basis:
      - Chimera
      - ManualChanges
      - SkipFutureEpisodes
      - SetDerivedDefaults
      - RedirectorProcessor

# Settings related to caching (reusing results for some time).
# The time before a change in the data propagates to clients is
# somewhere between min(source_data_ttl, feed_ttl) and
# source_data_ttl + feed_ttl.
caching:
  # Number of seconds to cache data obtained from outside
  source_data_ttl: 840  # 14 minutes
  # Number of seconds to let clients and the webserver cache the feed
  feed_ttl: 960  # 16 minutes
  # Number to multiply feed_ttl by when serving a show marked as complete
  completed_ttl_factor: 10.0
  # Number of seconds to let clients and the webserver cache the all episodes
  # feed
  all_episodes_ttl: 600  # 10 minutes

# Settings used for the part which ensures clients go through us to obtain
# an episode, so this host can be used to log such traffic.
redirector:
  # For the time being, this is separate from PostgreSQL and must point to
  # the sqlite file. It must either be an absolute path, or a path relative to
  # the root of the project (the podkast.radiorevolt.no/ folder).
  db_file: data/redirects.db

# Miscellaneous settings concerning the webserver
web:
  # URL to redirect to when the user accesses /
  official_website: https://radiorevolt.no

# Miscellaneous settings for the feed generation
feed:
  # Information about who owns this podcast (this will be public!)
  owner:
    name: "Radio Revolt"
    mail: "it@radiorevolt.no"
  # Metadata for the special feed with all episodes. You may use any Podcast
  # attributes, as documented in http://podgen.readthedocs.io/en/latest/user/basic_usage_guide/part_1.html
  metadata_all_episodes:
    name: "Alle podkastene til Radio Revolt"
    description: "Alle podkastepisodene fra Radio Revolt, samlet i én podkast."
    image: null

# Show names which map to the special "all episodes" feed
# (the canonical name is "all", these will all redirect there)
all_episodes_show_aliases:
  - alleepisoder
  - allepisodes
  - "*"
  - alle-podkaster
